### PR TITLE
Update library capsule and logo

### PR DESCRIPTION
**Pull request by DeeJayLSP**
Follow up for #29. I had to figure out which assets were being used in Steam.

The Logo has shadows. Once again, SVGs are provided.

### CODE REVIEW

**Review by jss2a98aj — CHANGES_REQUESTED** [review]
I think Steam does not allow "game" in the title, which is why previous versions of the capsule were lacking it.

**Comment by DeeJayLSP** [comment]
> I think Steam does not allow "game" in the title.

image

[There is over a thousand Steam entries with "Game" on the title.](https://steamdb.info/search/?a=all&q=Game) I highly doubt they don't allow it.

Also, this is only for the logos, not the title. We should maintain consistency.

**Comment by jss2a98aj** [comment]
> [There is over a thousand Steam entries with "Game" on the title.](https://steamdb.info/search/?a=all&q=Game) I highly doubt they don't allow it.
> 
> Also, this is only for the logos, not the title. We should maintain consistency.

That is strange, as we had to change the title from Blazium Game Engine to Blazium Engine on Steam to get approval. @Starkium should know more, as he is the one that has been handling the Steam upload.

**Comment by Starkium** [comment]
Since we're approved now, we can likely change it back, not an issue though

**Pull request merged**
